services:
  website:
    container_name: "achievements-website"
    build: .
    expose:
      - "80"
    restart: always
    environment:
      - "VIRTUAL_HOST=achievements.max-schluer.de,www.achievements.max-schluer.de"
      - "LETSENCRYPT_HOST=achievements.max-schluer.de,www.achievements.max-schluer.de"
    healthcheck:
      test: curl --fail https://achievements.max-schluer.de/ || exit 1
      interval: 5m
      timeout: 3s
      retries: 0
    networks:
      - rproxy

networks:
  rproxy:
    name: rproxy
    external: true
